### ISSUE TITLE
"Please specify a pdf in your todo list." is ambiguous 

### ISSUE THREAD

**Issue by hampelm** [detroitledger/grantentry#7]
Where is my todo list? Does this mean I don't have any grants in my queue? Also probably shouldn't be repeated twice. Maybe this is something I can quick tackle!

**Comment by bnchdrff** [comment]
we need to design & implement a widget for choosing the active pdf (the current list of links doesn't really work with more than two pdfs), and also we should come up with a quick and simple system for handling and displaying runtime messages. these can be two separate issues.
